version: '3.7'

services:
  webclient:
    user: node
    build: ./client
    volumes:
      - './client:/workdir'
    command: /bin/bash -c "while true; do echo faking deamon; sleep 60; done"
  web:
    volumes:
      - ./kernel/static:/app/static
    env_file:
      - ./kernel/.env
    build: ./kernel
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - ./kernel/static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
